version: "3.9"
services:
  flaskapi:
    container_name: flaskapi
    image: flaskapi
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgresdb:5432/postgres
    depends_on:
     - postgresdb

  postgresdb:
    container_name: postgresdb
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}

